# Generated by Django 5.0.7 on 2024-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="refresh",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
