# Generated by Django 5.0.7 on 2024-08-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_access_user_is_deleted_user_refresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_avatar",
            field=models.URLField(
                default="https://res.cloudinary.com/kay-development/image/upload/v1679787683/important/brad_dozo7x.jpg"
            ),
        ),
    ]
