# fly.toml app configuration file generated for estore-drf on 2024-10-26T22:19:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'estore-drf'
primary_region = 'ams'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'sh release.sh'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
