# Generated by Django 5.0.7 on 2024-07-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_message_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
