# Generated by Django 5.0.7 on 2024-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_alter_subscriber_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitedetail",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
