# Generated by Django 5.0.7 on 2024-08-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_message_is_deleted_sitedetail_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="sitedetail",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="is_deleted",
        ),
    ]
