DELIVERY_STATUS_CHOICES = (
    ("PENDING", "PENDING"),
    ("PACKING", "PACKING"),
    ("SHIPPING", "SHIPPING"),
    ("ARRIVING", "ARRIVING"),
    ("SUCCESS", "SUCCESS"),
)

PAYMENT_STATUS_CHOICES = (
    ("PENDING", "PENDING"),
    ("PROCESSING", "PROCESSING"),
    ("SUCCESSFUL", "SUCCESSFUL"),
    ("CANCELLED", "CANCELLED"),
    ("FAILED", "FAILED"),
)

PAYMENT_GATEWAY_CHOICES = (
    ("PAYSTACK", "PAYSTACK"),
    ("PAYPAL", "PAYPAL"),
)

RATING_CHOICES = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))
