# Generated by Django 5.0.7 on 2024-08-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="color",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="country",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="review",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="size",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="is_deleted",
        ),
    ]
