# Generated by Django 5.0.7 on 2024-09-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0003_seller_delete_sellerapplication"),
        ("shop", "0004_remove_order_shipping_address_order_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="sellers.seller",
            ),
        ),
    ]
